# Generated by Django 3.0.4 on 2020-10-29 06:28

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=froala_editor.fields.FroalaField(max_length=500, verbose_name='Comment'),
        ),
    ]
